keys = [
    "alerts",
    "news",
    "cetusCycle",
    "sortie",
    "archonHunt",
    "voidTraders",
    # "voidTraderItem",
    "steelPath",
    # "fissures",
    # "invasions",
    "duviriCycle",
    "deepArchimedea",
    "temporalArchimedea",
]
